spring:
  application:
    name: api-gateway
server:
  port: 8083

zuul:
  sensitive-headers:
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds:2000
  auditevents:
    enabled:
management:
  endpoints:
    web:
      exposure:
        exclude:
  endpoint:
    env:
      enabled: true
