spring:
  application:
    name: api-gateway
server:
  port: 8083

zuul:
  routes:
    voting-server: /member/**
#      url: http://localhost:8080
    auth-center : /auth/**
 #     url : http://localhost:8086
  sensitive-headers:
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds:2000
