spring:
  application:
    name: api-gateway
server:
  port: 8082


zuul:
  routes:
    voting-server: /member/**
#      url: http://localhost:8080

eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMiliseconds:2000
